---
- name: Load OS dependent variables
  include_vars: "{{ item_vars }}"
  with_first_found:
    - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"
    - default.yml
  loop_control:
    loop_var: item_vars
  tags: ['package', 'configuration', 'service']

- name: OS is supported
  assert:
        that: os_supported == True

- name: Install repo packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ repo_packages }}"
  tags: package

- name: "Enable plugin"
  ini_file: dest=/etc/yum/pluginconf.d/priorities.conf section=main option=enabled value=1

- name: "Merge repo priority data"
  set_fact: repositories="{{ repositories + additional_repos }}"
  when: additional_repos is defined

- name: "Set repository priorities"
  ini_file:
    dest: "/etc/yum.repos.d/{{ item.0.name }}.repo"
    section: "{{ item.1.name }}"
    option: priority
    value: "{{ item.1.priority }}"
  with_subelements:
    - "{{ repositories }}"
    - priorities
