---
- name: Install system tweaks
  include_tasks: install.yml
  when: state|default('present') == 'present'
  tags: ['tweaks', 'installation' ]

- name: Uninstall system tweaks
  include_tasks: uninstall.yml
  when: state|default('present') == 'absent'
  tags: ['tweaks', 'deinstallation' ]
