---
- name: Uninstall - Delete file glob 
  find:
    path: "{{ sysctl_config_location }}"
    pattern: "10-*"
  register: files_to_delete

- name: Uninstall - Remove file glob
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ files_to_delete.files }}"
  notify:
    - Reload sysctl configuration
  tags: [ 'cleanup' , 'deinstallation' ]

