---
- name: Add IUS repository to /etc/yum.repos.d/
  yum_repository:
    name: ius
    file: ius
    description: IUS Community Packages for Enterprise Linux {{ ansible_distribution_major_version }} - $basearch
    mirrorlist: https://mirrors.iuscommunity.org/mirrorlist?repo=ius-{{ ansible_distribution|lower}}{{ ansible_distribution_major_version|lower }}&arch=$basearch&protocol=http
    gpgkey: http://dl.iuscommunity.org/pub/ius/IUS-COMMUNITY-GPG-KEY
    enabled: yes
    gpgcheck: yes
    priority: 15
    state: present
  when: ansible_os_family == "RedHat"

- name: Install - Ensure that the IUS Python3 packages are installed
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"
  tags: [ 'package' ]

- name: Create sym link python3
  file:
    src: "/usr/bin/python3.6"
    dest: "/usr/local/bin/python3"
    state: link

- name: Create sym link pip3
  file:
    src: "/usr/bin/pip3.6"
    dest: "/usr/local/bin/pip3"
    state: link

