---
- name: Install - Ensure that required vim-enhanced package is installed
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"
  tags: [ 'package' ]

- name: Copying vimrc
  copy:
        src: "vimrc"
        dest: "/etc/vimrc"
        owner: root
        group: root
        mode: 0444
        force: yes

- name: Set an alias for vi
  lineinfile:
      path: /etc/profile
      state: present
      regexp: '^alias vi="vim"$'
      line: 'alias vi="vim"'
  when: ansible_os_family == "RedHat"
