---
- name: Load OS dependent variables
  include_vars: "{{ item_vars }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - default.yml
  loop_control:
    loop_var: item_vars
  tags: 
    - development
    - vim
    - variables
    - vim-install

- name: OS is supported
  assert:
        that: os_supported == True

- name: Install vim package
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ vim_packages }}"
  tags: package

- name: Copying .vimrc into skel folder
  copy:
        src: "vimrc"
        dest: "/etc/skel/.vimrc"
        owner: root
        group: root
        mode: 0400
        force: yes

- name: Copying .vimrc into root folder
  copy:
        src: "vimrc"
        dest: "/root/.vimrc"
        owner: root
        group: root
        mode: 0400
        force: yes

- name: Set an alias for vi 
  lineinfile:
      path: /etc/profile
      state: present
      regexp: '^alias vi="vim"$'
      line: 'alias vi="vim"'

