---
- name: Load OS dependent tasks
  include_tasks: "{{ item_firewalld }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - default.yml
  loop_control:
    loop_var: item_firewalld
  tags: ['package', 'configuration', 'service']
