---
- name: Load OS dependent variables
  include_vars: "{{ item_vars }}"
  with_first_found:
    - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"
    - default.yml
  loop_control:
    loop_var: item_vars
  tags: ['package', 'configuration', 'service']

- name: OS is supported
  assert:
        that: os_supported == True

- name: Copying colors.sh
  copy:
        src: "etc/profile.d/colors.sh"
        dest: "/etc/profile.d/colors.sh"
        owner: root
        group: root
        mode: 0644 
        force: yes

- name: Copying the Message of The Day file
  copy:
        src: "etc/motd.{{ ansible_distribution }}"
        dest: "/etc/motd.sh"
        owner: root
        group: root
        mode: 0555 
        force: yes

- name: Append motd.sh into BASH profile of root
  blockinfile:
    path: /root/.bash_profile
    block: |
        # Display Message of the Day
        if [ -f /etc/motd.sh ]; then
        /etc/motd.sh
        fi

- name: Append motd.sh into global BASH profile (skel)
  blockinfile:
    path: /etc/skel/.bash_profile
    block: |
        # Display Message of the Day
        if [ -f /etc/motd.sh ]; then
        /etc/motd.sh
        fi 

