---                                                                                                                                                          
- name: Load OS dependent variables
  include_vars: "{{ item_vars }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - default.yml
  loop_control:
    loop_var: item_vars
  tags: ['package', 'configuration', 'service']

- name: OS is supported
  assert:
        that: os_supported == True

- name: Install profile settings
  include_tasks: install.yml
  when: state|default('present') == 'present'
  tags: ['profiles', 'installation' ]

- name: Uninstall profile settings
  include_tasks: uninstall.yml
  when: state|default('present') == 'absent'
  tags: ['profiles', 'deinstallation' ]

