---                                                                                                                                                          
- name: Load OS dependent tasks
  include_tasks: "{{ item_profile }}"
  with_first_found:
    - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"
    - default.yml
  loop_control:
    loop_var: item_profile
  tags: ['package', 'configuration', 'service']

