---
- name: Load OS dependent variables
  include_vars: "{{ item_vars }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - default.yml
  loop_control:
    loop_var: item_vars
  tags: ['package', 'configuration', 'service']

- name: OS is supported
  assert:
        that: os_supported == True

- name: Install LLDpad service
  include_tasks: install.yml
  tags: ['package', 'installation', 'service']
  when: state|default('present') == 'present'

- name: Uninstall LLDpad service
  include_tasks: uninstall.yml
  when: state|default('present') == 'absent'
  tags: ['package', 'deinstallation' ]

