---
- name: Uninstall - Ensure that chronyd isn't installed.
  package:
    name: "{{ item }}"
    state: absent
  with_items: "{{ chrony_packages }}"
  tags: [ 'package' ]

- name: Uninstall - Remove chrony configuration and log files
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ delete_chrony_files }}"

- name: Install - Ensure that NTP packages are installed.
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ ntp_packages }}"
  tags: [ 'package' ]

- name: Ensure NTP is running and enabled as configured.
  service: 
    name: "{{ ntp_daemon }}"
    state: started
    enabled: yes
  when: ntp_enabled | bool
  tags: [ 'service ']

- name: Ensure NTP is stopped and disabled as configured.
  service:
    name: "{{ ntp_daemon }}"
    state: stopped
    enabled: no
  when: not ntp_enabled | bool

- name: Generate ntp.conf file
  template:
    src: etc/ntp.conf.j2
    dest: /etc/ntp.conf
  notify: restart ntp
  with_items: "{{ ntp_allow }}"
  when: ntp_enabled | bool

- name: Generate ntpd file
  template:
    src: etc/sysconfig/ntpd.j2
    dest: /etc/sysconfig/ntpd
  when: ntp_enabled | bool and ansible_os_family == "RedHat"


