---
- name: Setup hosts & hostname
  include_tasks: install.yml
  when: state|default('present') == 'present'
  tags: ['package', 'installation' ]

- name: Unset hosts
  include_tasks: uninstall.yml
  when: state|default('present') == 'absent'
  tags: ['package', 'deinstallation' ]
